Accept stage codes
metanorma/pubid-iso pull request #112
Opened 2022-09-21 07:22 UTC by mico

closes #110

2022-09-21 07:37 UTC, ronaldtse requested changes

2022-09-22 07:39 UTC, ronaldtse commented on lib/pubid/iso/stage.rb
> +        Stage.new(harmonized_code: stage)
@mico we are almost there. There are some code combinations that are not allowed, that's why I want you to encode ALL the valid codes. For example, 10.92, 10.93, 20.92 are invalid. Also 60.20, 60.9X, 95.00 are invalid.

2022-09-22 07:42 UTC, ronaldtse commented on lib/pubid/iso/stage.rb
> +        Stage.new(harmonized_code: stage)
Hmm it looks like you do have tests for the invalid codes. How are you rejecting those?

2022-09-22 08:52 UTC, mico commented on lib/pubid/iso/stage.rb
> +        Stage.new(harmonized_code: stage)
> Hmm it looks like you do have tests for the invalid codes. How are you rejecting those?

I'm using DESCRIPTIONS list from https://github.com/metanorma/pubid-iso/blob/main/lib/pubid/iso/harmonized_stage_code.rb#L6

2022-09-22 08:59 UTC, ronaldtse commented on lib/pubid/iso/stage.rb
> +        Stage.new(harmonized_code: stage)
Thank you! That's perfect!

2022-09-22 09:00 UTC, merged