Add more tests for recommendations type
metanorma/pubid-iso pull request #187
Opened 2023-01-06 09:32 UTC by mico

closes #183

2023-01-06 15:51 UTC, ronaldtse requested changes

2023-01-06 15:51 UTC, ronaldtse commented on spec/pubid_iso/identifier_spec.rb
> +      let(:pubid) { "ISO/R 657-IV" }
The formal (new style) pubid is actually "[ISO/R 657-4:1969](https://www.iso.org/standard/4795.html)"

2023-01-06 15:51 UTC, ronaldtse commented on spec/pubid_iso/identifier_spec.rb
> +      let(:pubid) { "ISO/R 300-III-1968" }
The official pubid is [ISO/R 300-3:1968](https://www.iso.org/standard/4232.html)

2023-01-06 15:51 UTC, ronaldtse commented on spec/pubid_iso/identifier_spec.rb
> +      let(:pubid) { "ISO/R 93-1-1963" }
The official pubid is [ISO/R 93-1:1963](https://www.iso.org/standard/3752.html).

We will need to implement a Roman numeral conversion for the old style part numbers.

2023-01-07 02:13 UTC, ronaldtse commented
@mico can you help implement the above comments? Thanks.

2023-01-15 07:26 UTC, mico commented
> @mico can you help implement the above comments? Thanks.

@ronaldtse done

2023-01-16 02:24 UTC, ronaldtse commented
Thank you @mico !

2023-01-16 02:24 UTC, ronaldtse approved these changes

2023-01-16 02:24 UTC, merged